version: '3'
services:
  mysql:
    image: mysql:5.7
    # platform: linux/amd64
    environment:
      MYSQL_DATABASE: development
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    # 文字化け対応
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3308:3306
