version: '3'
services:
  mysql:
    image: mysql:5.7
    # platform: linux/amd64
    environment:
      MYSQL_DATABASE: development
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    # 文字化け対応
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # 永続化
    volumes:
      - mysql-go:/var/lib/mysql
      - ./initsql:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql -> ローカルにdataディレクトリが作成される
    ports:
      - 3308:3306
  app:
    build: .
    tty: true
    volumes:
      - ./app:/go/src/app
    depends_on:
      - mysql

# volumeに名前をつける
volumes:
  mysql-go:
    name: mysql-go
