version: '3'
services:
  mysql:
    image: mysql:5.7
    # platform: linux/amd64
    environment:
      MYSQL_DATABASE: development
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
